# Generated by Django 5.2.7 on 2025-10-31 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("linkedin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete).",
                    ),
                ),
                ("sentiment_score", models.FloatField()),
                ("sentiment_details", models.JSONField(default=dict)),
                ("topics", models.JSONField(default=list)),
                ("topic_scores", models.JSONField(default=dict)),
                ("readability_score", models.FloatField()),
                ("readability_metrics", models.JSONField(default=dict)),
                ("tone", models.CharField(max_length=50)),
                ("tone_scores", models.JSONField(default=dict)),
                ("keywords", models.JSONField(default=list)),
                ("key_phrases", models.JSONField(default=list)),
                ("entities", models.JSONField(default=list)),
                ("language_quality_score", models.FloatField(default=0.0)),
                ("content_category", models.CharField(max_length=100)),
                ("analysis_version", models.CharField(max_length=50)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_analysis",
                        to="linkedin.linkedinpost",
                    ),
                ),
            ],
            options={
                "db_table": "content_analysis",
            },
        ),
        migrations.CreateModel(
            name="EngagementPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete).",
                    ),
                ),
                ("predicted_engagement_rate", models.FloatField()),
                ("success_probability", models.FloatField()),
                ("confidence_score", models.FloatField()),
                ("recommended_posting_time", models.DateTimeField()),
                ("time_sensitivity", models.FloatField(default=0.0)),
                ("audience_match_score", models.FloatField(default=0.0)),
                ("viral_potential", models.FloatField(default=0.0)),
                ("improvement_suggestions", models.JSONField(default=list)),
                ("feature_importance", models.JSONField(default=dict)),
                ("model_version", models.CharField(max_length=50)),
                ("prediction_context", models.JSONField(default=dict)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="linkedin.linkedinpost",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_engagement_predictions",
            },
        ),
        migrations.CreateModel(
            name="AudienceInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete).",
                    ),
                ),
                ("demographic_data", models.JSONField(default=dict)),
                ("industry_distribution", models.JSONField(default=dict)),
                ("company_size_distribution", models.JSONField(default=dict)),
                ("job_functions", models.JSONField(default=dict)),
                ("geographic_distribution", models.JSONField(default=dict)),
                ("engagement_patterns", models.JSONField(default=dict)),
                ("active_times", models.JSONField(default=dict)),
                ("interests", models.JSONField(default=list)),
                ("period", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audience_insights",
                "indexes": [
                    models.Index(
                        fields=["user", "period"], name="audience_in_user_id_de5a61_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete).",
                    ),
                ),
                ("topic_name", models.CharField(max_length=255)),
                ("topic_keywords", models.JSONField(blank=True, default=list)),
                ("post_count", models.IntegerField(default=0)),
                (
                    "avg_engagement_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_topics",
                "ordering": ["-avg_engagement_rate"],
                "unique_together": {("user", "topic_name")},
            },
        ),
        migrations.CreateModel(
            name="HashtagPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete).",
                    ),
                ),
                ("hashtag", models.CharField(max_length=255)),
                ("usage_count", models.IntegerField(default=0)),
                ("total_engagement", models.IntegerField(default=0)),
                (
                    "avg_engagement_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashtag_performance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hashtag_performance",
                "ordering": ["-avg_engagement_rate"],
                "indexes": [
                    models.Index(
                        fields=["user", "-avg_engagement_rate"],
                        name="hashtag_per_user_id_3fa841_idx",
                    )
                ],
                "unique_together": {("user", "hashtag")},
            },
        ),
        migrations.CreateModel(
            name="TimeSeriesAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete).",
                    ),
                ),
                ("analysis_type", models.CharField(max_length=50)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("metrics", models.JSONField(default=dict)),
                ("trends", models.JSONField(default=dict)),
                ("seasonality", models.JSONField(default=dict)),
                ("anomalies", models.JSONField(default=list)),
                ("statistical_data", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "time_series_analysis",
                "indexes": [
                    models.Index(
                        fields=["user", "period_start", "period_end"],
                        name="time_series_user_id_13b37d_idx",
                    ),
                    models.Index(
                        fields=["analysis_type"], name="time_series_analysi_21ca02_idx"
                    ),
                ],
            },
        ),
    ]
