# Generated by Django 5.2.8 on 2025-12-01 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete).",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this session (from frontend)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="New Chat",
                        help_text="Title of the chat session, auto-generated from first message",
                        max_length=255,
                    ),
                ),
                (
                    "user_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Anonymous user identifier (for non-authenticated users)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last message in this session",
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(
                        default=0, help_text="Total number of messages in this session"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this chat session. Null for anonymous users.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete).",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        help_text="Who sent this message",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="The actual message content")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata (model, tokens, processing time, etc.)",
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The chat session this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="new_post.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-last_message_at"],
                name="new_post_ch_user_id_00be10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user_identifier", "-last_message_at"],
                name="new_post_ch_user_id_7ea0f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["session_id"], name="new_post_ch_session_761366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="new_post_ch_session_73a16e_idx"
            ),
        ),
    ]
