# Generated by Django 5.2.9 on 2026-01-04 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_post", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this record is active (soft delete).",
                    ),
                ),
                ("content", models.TextField(help_text="The post content/text")),
                (
                    "media_files",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata about uploaded media files (URLs, types, names)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        help_text="Current status of the post",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled time for posting (if scheduled)",
                        null=True,
                    ),
                ),
                (
                    "poll_data",
                    models.JSONField(
                        blank=True,
                        help_text="Poll question and options if post includes a poll",
                        null=True,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the post was published",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Draft Post",
                "verbose_name_plural": "Draft Posts",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-updated_at"],
                        name="new_post_dr_user_id_093477_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="new_post_dr_user_id_5e3756_idx",
                    ),
                ],
            },
        ),
    ]
