# Generated by Django 5.2.8 on 2025-12-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_onboarding_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linkedin_profile_picture",
            field=models.URLField(
                blank=True,
                help_text="LinkedIn profile picture URL from OAuth.",
                max_length=2048,
                null=True,
            ),
        ),
    ]
