# Generated by Django 5.2.9 on 2026-01-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_linkedin_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_access_token",
            field=models.CharField(
                blank=True,
                help_text="OAuth access token from Google.",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True,
                help_text="Google user ID for OAuth integration.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_profile_picture",
            field=models.URLField(
                blank=True,
                help_text="Google profile picture URL from OAuth.",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_refresh_token",
            field=models.CharField(
                blank=True,
                help_text="OAuth refresh token from Google.",
                max_length=2048,
                null=True,
            ),
        ),
    ]
