# Generated by Django 5.2.7 on 2025-10-31 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedInPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("linkedin_post_id", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Only"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("carousel", "Carousel"),
                            ("article", "Article"),
                        ],
                        max_length=50,
                    ),
                ),
                ("media_urls", models.JSONField(blank=True, default=list)),
                ("posted_at", models.DateTimeField(db_index=True)),
                ("likes_count", models.IntegerField(default=0)),
                ("comments_count", models.IntegerField(default=0)),
                ("shares_count", models.IntegerField(default=0)),
                ("impressions_count", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
                (
                    "engagement_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("mentions", models.JSONField(blank=True, default=list)),
                ("word_count", models.IntegerField(blank=True, null=True)),
                ("char_count", models.IntegerField(blank=True, null=True)),
                ("has_emoji", models.BooleanField(default=False)),
                ("has_cta", models.BooleanField(default=False)),
                ("has_question", models.BooleanField(default=False)),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("professional", "Professional"),
                            ("casual", "Casual"),
                            ("inspirational", "Inspirational"),
                            ("educational", "Educational"),
                            ("humorous", "Humorous"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "readability_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("topics", models.JSONField(blank=True, default=dict)),
                (
                    "embedding_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "linkedin_posts",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="EngagementSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_time", models.DateTimeField(db_index=True)),
                ("likes_count", models.IntegerField()),
                ("comments_count", models.IntegerField()),
                ("shares_count", models.IntegerField()),
                ("impressions_count", models.IntegerField()),
                (
                    "engagement_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="linkedin.linkedinpost",
                    ),
                ),
            ],
            options={
                "db_table": "engagement_snapshots",
                "ordering": ["-snapshot_time"],
            },
        ),
        migrations.AddIndex(
            model_name="linkedinpost",
            index=models.Index(
                fields=["user", "-posted_at"], name="linkedin_po_user_id_871293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="linkedinpost",
            index=models.Index(
                fields=["-engagement_rate"], name="linkedin_po_engagem_84f1d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagementsnapshot",
            index=models.Index(
                fields=["post", "-snapshot_time"], name="engagement__post_id_bd60fa_idx"
            ),
        ),
    ]
